// eslint-disable-next-line max-classes-per-file
import Constants from './Constants';

class APIConstants {
    static apiTimeout = 120000;

    static baseUrl = Constants.getBaseUrl();

    static userContext = `${APIConstants.baseUrl}/user`;

    static companyContext = `${APIConstants.baseUrl}/company`;

    static templateContext = `${APIConstants.baseUrl}/template`;

    static bulkContext = `${APIConstants.baseUrl}/bulk`;

    static employeeContext = `${APIConstants.baseUrl}/employee`;

    static payrollContext = `${APIConstants.baseUrl}/payroll`;

    static attendanceContext = `${APIConstants.baseUrl}/attendance`;

    static shiftsContext = `${APIConstants.baseUrl}/attendance/company`;

    static leaveContext = `${APIConstants.baseUrl}/leave`;

    static metadataContext = `${APIConstants.baseUrl}/metadata`;

    static taskContext = `${APIConstants.baseUrl}/task`;

    static jobOpeningContext = `${APIConstants.baseUrl}`;

    static courseContext = `${APIConstants.baseUrl}/course`;

    static employeeLifeCycleContext = `${APIConstants.baseUrl}/employee-life-cycle`;

    static employeeExpenseDetailsContext = `${APIConstants.baseUrl}`;

    static companyExpenseDetailsContext = `${APIConstants.baseUrl}/expense`;

    static managementExpenseDetailsContext = `${APIConstants.baseUrl}/expense`;

    static notificationsContext = `${APIConstants.baseUrl}/notification`;

    static messengerContext = `${APIConstants.baseUrl}/chatroom`;

    static helpdeskContext = `${APIConstants.baseUrl}/helpdesk`;

    static iamContext = `${APIConstants.baseUrl}/iam`;

    static companyPolicyDocument = `${APIConstants.baseUrl}/policy`;

    static employeeIdentityDocument = `${APIConstants.baseUrl}/document`;

    static tdsContext = `${APIConstants.baseUrl}/tds`;

    static letterContext = `${APIConstants.baseUrl}/letter`;

    static inquiryFormContext = `${APIConstants.baseUrl}/inquiry/form`;

    static endPoints = {
        iam: {
            self: APIConstants.iamContext,
            companyUserAccess: `${APIConstants.iamContext}/company/user/access`,
            companyPlanAccess: `${APIConstants.iamContext}/company/plan/access`,
            companyUserRoles: `${APIConstants.iamContext}/company/user/roles`,
            companyEmployeeRoles: `${APIConstants.iamContext}/company/employee/roles`,
            companyRoles: `${APIConstants.iamContext}/company/roles`,
        },
        user: {
            self: APIConstants.userContext,
            lookup: `${APIConstants.userContext}/lookup`,
            login: `${APIConstants.userContext}/login`,
            signup: `${APIConstants.userContext}/signup`,
            verify: `${APIConstants.userContext}/otpVerify`,
            update: `${APIConstants.userContext}/update-profile`,
            logout: `${APIConstants.userContext}/logout`,
            resetPin: `${APIConstants.userContext}/reset-pin`,
            forgotPin: `${APIConstants.userContext}/forgot-pin`,
            otpSend: `${APIConstants.userContext}/otpSend`,
            companies: `${APIConstants.userContext}/companies`,
            addFamilyDetails: `${APIConstants.userContext}/family-details/add`,
            editFamilyDetails: `${APIConstants.userContext}/family-details/edit`,
            companyRegistrations: `${APIConstants.userContext}/company-registrations`,
            addCompanyRegistration: `${APIConstants.userContext}/company-registration/add`,
            companyRoles: `${APIConstants.userContext}/company/roles`,
            profileImage: `${APIConstants.userContext}/upload/profile/image`,
            globalUserImage: `${APIConstants.userContext}/profile/pic`,
            uploadResume: `${APIConstants.userContext}/resume`,
            personalDetails: `${APIConstants.userContext}/personal-details/edit`,
            addContactDetails: `${APIConstants.userContext}/contact-details/add`,
            editContactDetails: `${APIConstants.userContext}/contact-details/edit`,
            addPreviousEmployments: `${APIConstants.userContext}/work-history/add`,
            editPreviousEmployments: `${APIConstants.userContext}/work-history/edit`,
            biometricDetails: `${APIConstants.userContext}/biometric-details/edit`,
            addEducationDetails: `${APIConstants.userContext}/education-details/add`,
            editEducationDetails: `${APIConstants.userContext}/education-details/edit`,
            addSkills: `${APIConstants.userContext}/skills/add`,
            editSkills: `${APIConstants.userContext}/skills/edit`,
            getMyProfile: `${APIConstants.userContext}/my-profile`,
            addTrainingCertificates: `${APIConstants.userContext}/training-certificates/add`,
            editTrainingCertificates: `${APIConstants.userContext}/training-certificates/edit`,
            userRoles: `${APIConstants.userContext}/company/all/roles`,
        },
        bulk: {
            downloadTemplate: `${APIConstants.bulkContext}/download/bulk`,
            upload: `${APIConstants.bulkContext}/upload`,
            downloadData: `${APIConstants.bulkContext}/download/content`,
        },
        template: {
            templateByType: `${APIConstants.templateContext}/get/by/type`,
            loadCompanyTemplates: `${APIConstants.templateContext}/get/by/company`,
            addTemplate: `${APIConstants.templateContext}/add`,
            updateTemplate: `${APIConstants.templateContext}/update`,
            templateKeys: `${APIConstants.templateContext}/keys/general`,
            generalTemplateKeys: `${APIConstants.templateContext}/general/keys`,
            sendAppointmentMail: `${APIConstants.templateContext}/appointment-email/generate`,
            templatesTypes: `${APIConstants.templateContext}/get/types`,
            templateDetails: `${APIConstants.templateContext}/get/by/type`,
            systemTemplates: `${APIConstants.templateContext}/global/get`,
            companyTemplateCount: `${APIConstants.templateContext}/get/types/count`,
            systemTemplateCount: `${APIConstants.templateContext}/get/global/types/count`,
        },
        letter: {
            jobOfferPdfGenerate: `${APIConstants.letterContext}/offer/generate`,
            jobAppointmentPdfGenerate: `${APIConstants.letterContext}/appointment/generate`,
            viewDocument: `${APIConstants.letterContext}/url`,
        },
        company: {
            employmentType: `${APIConstants.companyContext}/employment-type`,
            aliasCompany: `${APIConstants.companyContext}/alias-company`,
            roleTypes: `${APIConstants.companyContext}/role-types`,
            familyMember: `${APIConstants.companyContext}/family-member`,
            onBoardingDocumentChecklist: `${APIConstants.companyContext}/onBoarding-document-checklist`,
            grade: `${APIConstants.companyContext}/grade`,
            gradeEdit: `${APIConstants.companyContext}/grade/edit`,
            grades: `${APIConstants.companyContext}/grades`,
            gradesActivate: `${APIConstants.companyContext}/grades/activate`,
            gradesDeactivate: `${APIConstants.companyContext}/grades/deactivate`,
            payrollGroup: `${APIConstants.companyContext}/payroll-group`,
            businessFunction: `${APIConstants.companyContext}/business-function`,
            businessFunctionEdit: `${APIConstants.companyContext}/business-function/edit`,
            businessFunctions: `${APIConstants.companyContext}/business-functions`,
            businessFunctionsActivate: `${APIConstants.companyContext}/business-functions/activate`,
            businessFunctionsDeactivate: `${APIConstants.companyContext}/business-functions/deactivate`,
            separationReason: `${APIConstants.companyContext}/separationReason`,
            department: `${APIConstants.companyContext}/department`,
            departmentEdit: `${APIConstants.companyContext}/department/edit`,
            departments: `${APIConstants.companyContext}/departments`,
            departmentsActivate: `${APIConstants.companyContext}/departments/activate`,
            departmentsDeactivate: `${APIConstants.companyContext}/departments/deactivate`,
            designation: `${APIConstants.companyContext}/designation`,
            designationEdit: `${APIConstants.companyContext}/designation/edit`,
            designations: `${APIConstants.companyContext}/designations`,
            designationsActivate: `${APIConstants.companyContext}/designations/activate`,
            designationsDeactivate: `${APIConstants.companyContext}/designations/deactivate`,
            location: `${APIConstants.companyContext}/location`,
            locations: `${APIConstants.companyContext}/locations`,
            locationsActivate: `${APIConstants.companyContext}/locations/activate`,
            locationsDeactivate: `${APIConstants.companyContext}/locations/deactivate`,
            locationEdit: `${APIConstants.companyContext}/location/edit`,
            locationAddresses: `${APIConstants.companyContext}/locationAddresses`,
            locationAddressesEdit: `${APIConstants.companyContext}/locationAddresses/edit`,
            locationDetail: `${APIConstants.companyContext}/location/detail`,
            getAllAnnouncements: `${APIConstants.companyContext}/get/all/announcement`,
            getAnnouncement: `${APIConstants.companyContext}/get/announcement`,
            addAnnouncement: `${APIConstants.companyContext}/add/announcement`,
            updateAnnouncement: `${APIConstants.companyContext}/update/announcement`,
            holidays: `${APIConstants.companyContext}/get/holiday`,
            activeHolidays: `${APIConstants.companyContext}/get/holiday/active`,
            addHoliday: `${APIConstants.companyContext}/add/holiday`,
            editHoliday: `${APIConstants.companyContext}/edit/holiday`,
            logo: `${APIConstants.companyContext}/upload/profile`,
            directory: `${APIConstants.companyContext}/employees/directory/work-profile`,
            pfDetail: `${APIConstants.companyContext}/pf-detail`,
            esiDetail: `${APIConstants.companyContext}/esi-detail`,
            ptDetail: `${APIConstants.companyContext}/pt-detail`,
            lwfDetail: `${APIConstants.companyContext}/lwf-detail`,

            employees: {
                self: `${APIConstants.companyContext}/employees`,
                workProfile: `${APIConstants.companyContext}/employees/work-profile`,
                personalDetails: `${APIConstants.companyContext}/employees/personal-details`,
                contacts: `${APIConstants.companyContext}/employees/contact-details`,
                familyDetails: `${APIConstants.companyContext}/employees/family-details`,
                nominations: `${APIConstants.companyContext}/employees/nominations`,
                dependents: `${APIConstants.companyContext}/employees/dependents`,
                positions: `${APIConstants.companyContext}/employees/positions`,
                workHistory: `${APIConstants.companyContext}/employees/previous-employments`,
                statutoryDetails: `${APIConstants.companyContext}/employees/statutory-details`,
                biometricDetails: `${APIConstants.companyContext}/employees/biometric-details`,
                educationDetails: `${APIConstants.companyContext}/employees/education-details`,
                trainingAndCertifications: `${APIConstants.companyContext}/employees/training-certificates`,
                skills: `${APIConstants.companyContext}/employees/skills`,
                bankDetails: `${APIConstants.companyContext}/employees/bank-details`,
                basicSetup: `${APIConstants.companyContext}/employees/basic-setup`,
            },
        },
        employee: {
            getFullProfileById: `${APIConstants.employeeContext}/id`,
            getMyProfile: `${APIConstants.employeeContext}/my-profile`,
            editWorkProfile: `${APIConstants.employeeContext}/work-profile/edit`,
            addWorkProfile: `${APIConstants.employeeContext}/work-profile/add`,
            editPersonalDetails: `${APIConstants.employeeContext}/personal-details/edit`,
            addContactDetails: `${APIConstants.employeeContext}/contact-details/add`,
            editContactDetails: `${APIConstants.employeeContext}/contact-details/edit`,
            addFamilyDetails: `${APIConstants.employeeContext}/family-details/add`,
            editFamilyDetails: `${APIConstants.employeeContext}/family-details/edit`,
            addWorkHistory: `${APIConstants.employeeContext}/previous-employments/add`,
            editWorkHistory: `${APIConstants.employeeContext}/previous-employments/edit`,
            addStatutoryDetails: `${APIConstants.employeeContext}/statutory-details/add`,
            editStatutoryDetails: `${APIConstants.employeeContext}/statutory-details/edit`,
            addNominations: `${APIConstants.employeeContext}/nominations/add`,
            editNominations: `${APIConstants.employeeContext}/nominations/edit`,
            editBiometricDetails: `${APIConstants.employeeContext}/biometric-details/edit`,
            addEducationDetails: `${APIConstants.employeeContext}/education-details/add`,
            editEducationDetails: `${APIConstants.employeeContext}/education-details/edit`,
            addTrainingCertificates: `${APIConstants.employeeContext}/training-certificates/add`,
            editTrainingCertificates: `${APIConstants.employeeContext}/training-certificates/edit`,
            addSkills: `${APIConstants.employeeContext}/skills/add`,
            editSkills: `${APIConstants.employeeContext}/skills/edit`,
            myList: `${APIConstants.employeeContext}/my-list`,
            celebrations: `${APIConstants.employeeContext}/celebrations`,
            kinsBirthday: `${APIConstants.employeeContext}/family/birthdays`,
            profilePics: `${APIConstants.employeeContext}/get-employee-images`,
            employeesImages: `${APIConstants.employeeContext}/get-employee-images`,
            employeeAttribute: `${APIConstants.employeeContext}/attributes`,
            onNoFamilyDetail: `${APIConstants.employeeContext}/personal-details/declare-no-family`,
            loadSignatoryAuthorities: `${APIConstants.employeeContext}/signature/get/all`,
            addEmployeeSignature: `${APIConstants.employeeContext}/signature/add`,
            updateEmployeeSignature: `${APIConstants.employeeContext}/signature/update`,
            loadAttendanceAttribute: `${APIConstants.employeeContext}/attributes/attendance`,
            loadAllAttendanceAttribute: `${APIConstants.employeeContext}/attributes/attendance/all`,
            postAttendanceAttribute: `${APIConstants.employeeContext}/attributes/attendance`,
            downloadAttendanceAttributes: `${APIConstants.employeeContext}/attributes/attendance/download`,
            uploadAttendanceAttributes: `${APIConstants.employeeContext}/attributes/attendance/upload`,
            downloadAliasCompanyBulk: `${APIConstants.employeeContext}/alias-company/download`,
            uploadAliasCompanyBulk: `${APIConstants.employeeContext}/alias-company/upload`,
            epfActiveDetail: `${APIConstants.employeeContext}/epf/active`,
            esiActiveDetail: `${APIConstants.employeeContext}/esi/active`,
            ptActiveDetail: `${APIConstants.employeeContext}/pt/active`,
            lwfActiveDetail: `${APIConstants.employeeContext}/lwf/active`,
            epfDetail: `${APIConstants.employeeContext}/epf/current`,
            esiDetail: `${APIConstants.employeeContext}/esi/current`,
            lwfDetail: `${APIConstants.employeeContext}/lwf/current`,
            ptDetail: `${APIConstants.employeeContext}/pt/current`,
            epfSheetDownload: `${APIConstants.employeeContext}/epf/sheet/download`,
            esiSheetDownload: `${APIConstants.employeeContext}/esi/sheet/download`,
            ptSheetDownload: `${APIConstants.employeeContext}/pt/sheet/download`,
            lwfSheetDownload: `${APIConstants.employeeContext}/lwf/sheet/download`,
            epfSheetUpload: `${APIConstants.employeeContext}/epf/sheet/upload`,
            esiSheetUpload: `${APIConstants.employeeContext}/esi/sheet/upload`,
            ptSheetUpload: `${APIConstants.employeeContext}/pt/sheet/upload`,
            lwfSheetUpload: `${APIConstants.employeeContext}/lwf/sheet/upload`,
            viewEmployeeWorkHistoryAttachment: `${APIConstants.employeeContext}/previous-employments/url`,
            viewEmployeeEducationAttachment: `${APIConstants.employeeContext}/education-details/url`,
        },
        payroll: {
            dashboard: `${APIConstants.payrollContext}/dashboard`,
            companyComponents: `${APIConstants.payrollContext}/company/components`,
            companyTagComponents: `${APIConstants.payrollContext}/company/components/tag`,
            downloadSalaryStructureTemplate: `${APIConstants.payrollContext}/download/employee-salary-structure`,
            uploadSalaryStructure: `${APIConstants.payrollContext}/upload/employee-salary-structure`,
            employeesSalaryDetails: `${APIConstants.payrollContext}/company/employees/salary-details`,
            employeesSalaryRevisions: `${APIConstants.payrollContext}/company/employee/salary-revisions`,
            payrollGroups: `${APIConstants.payrollContext}/company/pay-groups`,
            allPayrollGroups: `${APIConstants.payrollContext}/company/pay-groups/all`,
            payGroupEmployees: `${APIConstants.payrollContext}/company/non-pay-group/employees`,
            payCyclesByYear: `${APIConstants.payrollContext}/pay-cycles/group/year`,
            processProvisional: `${APIConstants.payrollContext}/company/pay-cycle/process-provisional`,
            updateNonPayableData: `${APIConstants.payrollContext}/company/pay-cycle/update/non-payable`,
            updateComplianceData: `${APIConstants.payrollContext}/company/pay-cycle/update-compliance`,
            updateVariableEarningData: `${APIConstants.payrollContext}/company/pay-cycle/update-earnings`,
            updateDeductionsData: `${APIConstants.payrollContext}/company/pay-cycle/update-deductions`,
            updateIncomeTaxData: `${APIConstants.payrollContext}/company/pay-cycle/update-income-tax`,
            finalizePayCycle: `${APIConstants.payrollContext}/company/pay-cycle/finalize`,
            markAsPaid: `${APIConstants.payrollContext}/company/pay-cycle/mark-paid`,
            generatePayCycles: `${APIConstants.payrollContext}/company/pay-cycle/generate`,
            validateEmployeesList: `${APIConstants.payrollContext}/company/pay-cycle/validate`,
            regeneratePayroll: `${APIConstants.payrollContext}/company/pay-cycle/re-generate`,
            viewPayCycle: `${APIConstants.payrollContext}/company/pay-cycle/get`,
            editEmployeesInPayrollGroup: `${APIConstants.payrollContext}/company/pay-group/employees`,
            downloadNonPayableData: `${APIConstants.payrollContext}/company/pay-cycle/download/non-payable`,
            uploadNonPayableData: `${APIConstants.payrollContext}/company/pay-cycle/upload/non-payable`,
            downloadVariableEarningData: `${APIConstants.payrollContext}/company/pay-cycle/download/variable-earnings`,
            uploadVariableEarningData: `${APIConstants.payrollContext}/company/pay-cycle/upload/variable-earnings`,
            downloadDeductionsData: `${APIConstants.payrollContext}/company/pay-cycle/download/deductions`,
            uploadDeductionsData: `${APIConstants.payrollContext}/company/pay-cycle/upload/deductions`,
            downloadIncomeTaxData: `${APIConstants.payrollContext}/company/pay-cycle/download/income-tax`,
            downloadComplianceData: `${APIConstants.payrollContext}/company/pay-cycle/download/compliance`,
            downloadUtrSheet: `${APIConstants.payrollContext}/company/pay-cycle/download/utr`,
            uploadUtrSheet: `${APIConstants.payrollContext}/company/pay-cycle/upload/utr`,
            uploadIncomeTaxData: `${APIConstants.payrollContext}/company/pay-cycle/upload/income-tax`,
            uploadComplianceData: `${APIConstants.payrollContext}/company/pay-cycle/upload/compliance`,
            downloadFullSheet: `${APIConstants.payrollContext}/company/pay-cycle/download/full-sheet`,
            employeePaySlips: `${APIConstants.payrollContext}/pay-slips/employee/year`,
            downloadPaySlip: `${APIConstants.payrollContext}/pay-slip/employee/pay-cycle`,
            employeeSalaryDetails: `${APIConstants.payrollContext}/company/employee/salary-details`,
            estimatedLiveSalary: `${APIConstants.payrollContext}/employee/live/salary`,
            pfComponents: `${APIConstants.payrollContext}/company/pf/components`,
            applicablePfComponents: `${APIConstants.payrollContext}/pf/applicable/components`,
            applicableEsiComponents: `${APIConstants.payrollContext}/esi/applicable/components`,
            activatePfComponents: `${APIConstants.payrollContext}/company/pf/components`,
            activateEsiComponents: `${APIConstants.payrollContext}/company/esi/components`,
            esiComponents: `${APIConstants.payrollContext}/company/esi/components`,

        },
        shifts: {
            shifts: `${APIConstants.shiftsContext}/shifts`,
            addShifts: `${APIConstants.shiftsContext}/shift/add`,
            editShifts: `${APIConstants.shiftsContext}/shift/edit`,
        },
        attendance: {
            save: `${APIConstants.attendanceContext}/save`,
            regularize: `${APIConstants.attendanceContext}/regularize`,
            approveRegularizeAttendance: `${APIConstants.attendanceContext}/regularize/approve`,
            rejectRegularizeAttendance: `${APIConstants.attendanceContext}/regularize/reject`,
            status: `${APIConstants.attendanceContext}/status`,
            month: `${APIConstants.attendanceContext}/employee/attendance/month`,
            check: `${APIConstants.attendanceContext}/check`,
            statistics: `${APIConstants.attendanceContext}/employee/attendance/month/statistics`,
            shiftsMapping: `${APIConstants.attendanceContext}/employee/shift-mappings`,
            shiftsMappingAdd: `${APIConstants.attendanceContext}/employee/shift-mappings/add`,
            getShift: `${APIConstants.attendanceContext}/company/shift/id`,
            attendanceMapping: `${APIConstants.attendanceContext}/team/attendance/month`,
            myTeamAttendanceMapping: `${APIConstants.attendanceContext}/team/attendance/date`,
            attendanceSummary: `${APIConstants.attendanceContext}/get/attendance-summary`,
            pendingRequests: `${APIConstants.attendanceContext}/get/pending/regularize`,
            updatePendingRequest: `${APIConstants.attendanceContext}/update/pending/regularize`,
            withdrawPendingRequest: `${APIConstants.attendanceContext}/withdraw/pending/regularize`,
            dailyAttendanceReport: `${APIConstants.attendanceContext}/daily/report`,
            monthlyAttendanceReport: `${APIConstants.attendanceContext}/monthly/report`,
            dashboard: `${APIConstants.attendanceContext}/dashboard`,

        },
        leave: {
            definitions: `${APIConstants.leaveContext}/company/definitions`,
            apply: `${APIConstants.leaveContext}/apply`,
            modify: `${APIConstants.leaveContext}/modify`,
            approve: `${APIConstants.leaveContext}/approve`,
            reject: `${APIConstants.leaveContext}/not-approve`,
            withdraw: `${APIConstants.leaveContext}/withdraw`,
            balance: `${APIConstants.leaveContext}/balance`,
            add: `${APIConstants.leaveContext}/company/definition/add`,
            edit: `${APIConstants.leaveContext}/company/definition/edit`,
            teamBalance: `${APIConstants.leaveContext}/team/balance`,
            status: `${APIConstants.leaveContext}/employee/status`,
            history: `${APIConstants.leaveContext}/employee/history`,
            leaveSummary: `${APIConstants.leaveContext}/get/leave-summary`,
            bulkUpload: `${APIConstants.leaveContext}/upload/bulk`,
            bulkDownload: `${APIConstants.leaveContext}/download/bulk`,
            leaveStatsEmployeeWise: `${APIConstants.leaveContext}/get/leave/stats`,
            addLeaveDetailEmployeeWise: `${APIConstants.leaveContext}/add/leave-detail`,
            updateLeaveDetailEmployeeWise: `${APIConstants.leaveContext}/update/leave-detail`,
            leaveBalanceActive: `${APIConstants.leaveContext}/balance/active`,
            employeeLeaveDetail: `${APIConstants.leaveContext}/other/employee/history`,
            otherEmployeesLatestLeaves: `${APIConstants.leaveContext}/other/employee/latest`,
            otherEmployeesLedgerLeaves: `${APIConstants.leaveContext}/other/employee/ledger`,
            leaveDashboard: `${APIConstants.leaveContext}/company/dashboard`,
        },
        metadata: {
            all: `${APIConstants.metadataContext}/all`,
            add: `${APIConstants.metadataContext}/add`,
            type: `${APIConstants.metadataContext}/type`,
            typeAndStatus: `${APIConstants.metadataContext}/type/status`,
            companyAll: `${APIConstants.metadataContext}/company/all`,
            companyType: `${APIConstants.metadataContext}/company/type`,
            companyTypeAndStatus: `${APIConstants.metadataContext}/company/type/status`,
            companyAdd: `${APIConstants.metadataContext}/company/add`,
            companyValuesAdd: `${APIConstants.metadataContext}/company/values/add`,
            companyValuesEdit: `${APIConstants.metadataContext}/company/values/edit`,
            companyValuesActivate: `${APIConstants.metadataContext}/company/values/activate`,
            companyValuesDeactivate: `${APIConstants.metadataContext}/company/values/deactivate`,
            companyAllById: `${APIConstants.metadataContext}/company/all/id`,
        },
        tasks: {
            getTask: `${APIConstants.taskContext}/get/allocatedTask`,
            getTaskDetails: `${APIConstants.taskContext}/get/allocated-task/details`,
            getTaskCount: `${APIConstants.taskContext}/get/allocated-task/count`,
            taskReassign: `${APIConstants.taskContext}/reassign`,
        },
        jobOpening: {
            addJobOpening: `${APIConstants.jobOpeningContext}/job-opening/add`,
            jobOpeningSummary: `${APIConstants.jobOpeningContext}/job-opening/summary/date`,
            jobOpeningDetailByTaskId: `${APIConstants.jobOpeningContext}/job-opening/get/id`,
            approveJobOpening: `${APIConstants.jobOpeningContext}/job-opening/approve`,   // @deprecated
            approveTaskJobOpening: `${APIConstants.jobOpeningContext}/job-opening/approve/task`,
            rejectJobOpening: `${APIConstants.jobOpeningContext}/job-opening/reject`,   // @deprecated
            rejectTaskJobOpening: `${APIConstants.jobOpeningContext}/job-opening/reject/task`,
            reopenJobOpening: `${APIConstants.jobOpeningContext}/job-opening/reopen`,
            managerJobOpeningRequests: `${APIConstants.jobOpeningContext}/job-opening/get/manager`,
            closeJobOpening: `${APIConstants.jobOpeningContext}/job-opening/close`,
            publishJobOpening: `${APIConstants.jobOpeningContext}/job-opening/publish`,
            getJobOpeningDetail: `${APIConstants.jobOpeningContext}/job-opening/get`,
            loadCompanyCandidateCount: `${APIConstants.jobOpeningContext}/job-opening/application/status/count`,
            loadAllCompanyApplication: `${APIConstants.jobOpeningContext}/job-opening/application/get/all`,
            applicationsStatsCount: `${APIConstants.jobOpeningContext}/job-opening/application/shortlisted/count`,
            todaysScheduledRounds: `${APIConstants.jobOpeningContext}/job-opening/application/scheduled/round/today`,
            userGetJobOpeningDetail: `${APIConstants.jobOpeningContext}/job-opening/get/user`,
            getAllJobApplicationsFunnel: `${APIConstants.jobOpeningContext}/job-opening/applications/funnel`,
            myApplicationsJobOpening: `${APIConstants.jobOpeningContext}/job-opening/applications`,
            publicJobDetailByCode: `${APIConstants.jobOpeningContext}/job-opening/public`,
            applyForJob: `${APIConstants.jobOpeningContext}/job-opening/apply`,
            scheduleJobOpening: `${APIConstants.jobOpeningContext}/job-opening/application/screening/schedule`,
            scheduleJobOpeningMeeting: `${APIConstants.jobOpeningContext}/job-opening/application/screening/schedule/meeting`,
            shortListApplication: `${APIConstants.jobOpeningContext}/job-opening/application/shortlist`,
            rejectApplication: `${APIConstants.jobOpeningContext}/job-opening/application/reject`,
            holdApplication: `${APIConstants.jobOpeningContext}/job-opening/application/hold`,
            loadScreeningSchedules: `${APIConstants.jobOpeningContext}/job-opening/application/screening/schedules`,
            loadScreeningSchedulesHistory: `${APIConstants.jobOpeningContext}/job-opening/application/screening/schedules/history`,
            completedRound: `${APIConstants.jobOpeningContext}/job-opening/application/completed/round`,
            roundCount: `${APIConstants.jobOpeningContext}/job-opening/application/round/count`,
            loadHiringTeam: `${APIConstants.jobOpeningContext}/job-opening/application/team`,
            giveScreeningFeedback: `${APIConstants.jobOpeningContext}/job-opening/application/feedback/add`,
            getKanbanJobOpeningDetail: `${APIConstants.jobOpeningContext}/job-opening/application/hiring/setup`,
            viewResume: `${APIConstants.jobOpeningContext}/job-opening/application/resume`,
            hiringDecision: `${APIConstants.jobOpeningContext}/job-opening/application/hiring/decision`,
            applicationStatusChange: `${APIConstants.jobOpeningContext}/job-opening/application/status/change`,
            addRecuriters: `${APIConstants.jobOpeningContext}/job-opening/add/recruiter`,
            updateJobOpening: `${APIConstants.jobOpeningContext}/job-opening/update`,
            generateWithAi: `${APIConstants.jobOpeningContext}/job-opening/ai/jd/generate`,
            getDashboardData: `${APIConstants.jobOpeningContext}/job-opening/hiring/dashboard`,
        },
        course: {
            addCategory: `${APIConstants.courseContext}/category/add`,
            loadCategories: `${APIConstants.courseContext}/categories/all`,
            addCourse: `${APIConstants.courseContext}/save`,
            getCourseById: `${APIConstants.courseContext}/by`,
            loadAllCourses: `${APIConstants.courseContext}/all`,
            saveSections: `${APIConstants.courseContext}/module/add`,
        },
        employeeLifeCycle: {
            loadDataForSeparation: `${APIConstants.employeeLifeCycleContext}/employee-data-for-separation`,
            viewSeparationAttachment: `${APIConstants.employeeLifeCycleContext}/separation/url`,
            viewWorkHistoryAttachment: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/work-history-url`,
            viewEducationAttachment: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/url-education`,
            initiateSeparation: `${APIConstants.employeeLifeCycleContext}/initiate/separation`,
            deactivationDetail: `${APIConstants.employeeLifeCycleContext}/get-employee-deactivation-detail`,
            withdrawSeparation: `${APIConstants.employeeLifeCycleContext}/withdraw/separation`,
            separationTasks: `${APIConstants.employeeLifeCycleContext}/separations/status`,
            approveSeparation: `${APIConstants.employeeLifeCycleContext}/approve/separation`,
            approveWithdrawSeparation: `${APIConstants.employeeLifeCycleContext}/approve/withdraw/separation`,
            notApproveSeparation: `${APIConstants.employeeLifeCycleContext}/not-approve/separation`,
            notApproveWithdrawSeparation: `${APIConstants.employeeLifeCycleContext}/not-approve/withdraw/separation`,
            initiateAbsconding: `${APIConstants.employeeLifeCycleContext}/initiate/abscond`,
            loadInitiateAbsconding: `${APIConstants.employeeLifeCycleContext}/initiate/abscond`,
            closeAbscondingNotification: `${APIConstants.employeeLifeCycleContext}/reject/absconding/notification/task`,
            getAbscondingTasks: `${APIConstants.employeeLifeCycleContext}/get-absconding-task`,
            approveAbsconding: `${APIConstants.employeeLifeCycleContext}/approve/abscond`,
            rejectAbsconding: `${APIConstants.employeeLifeCycleContext}/non-approve/abscond`,
            initiateTransfer: `${APIConstants.employeeLifeCycleContext}/transfer/request`,
            transferTasks: `${APIConstants.employeeLifeCycleContext}/get-transfer-task`,
            approveTransfer: `${APIConstants.employeeLifeCycleContext}/approve/transfer`,
            rejectTransfer: `${APIConstants.employeeLifeCycleContext}/not-approve/transfer`,
            loadConfirmations: `${APIConstants.employeeLifeCycleContext}/confirmation/get-pending`,
            workHistories: `${APIConstants.employeeLifeCycleContext}/get-employee-work-history`,
            initiateJobOffer: `${APIConstants.employeeLifeCycleContext}/job-offer/initiate`,
            updateInitiatedJobOffer: `${APIConstants.employeeLifeCycleContext}/job-offer/update`,
            initiateOfferingData: `${APIConstants.employeeLifeCycleContext}/job-offer/save/offer-data`,
            updateInitiatedOfferingData: `${APIConstants.employeeLifeCycleContext}/job-offer/update/offer-data`,
            initiateOfferComparison: `${APIConstants.employeeLifeCycleContext}/job-offer/save/offer-comparison`,
            updateInitiatedOfferComparison: `${APIConstants.employeeLifeCycleContext}/job-offer/update/offer-comparison`,
            saveCtcStructureStatutory: `${APIConstants.employeeLifeCycleContext}/job-offer/save/statutory-detail`,
            updateCtcStructureStatutory: `${APIConstants.employeeLifeCycleContext}/job-offer/update/statutory-detail`,
            removeStatutoryComponent: `${APIConstants.employeeLifeCycleContext}/job-offer/remove/statutory-component`,
            saveCtcStructureCompliance: `${APIConstants.employeeLifeCycleContext}/job-offer/save/compliance-detail`,
            updateCtcStructureCompliance: `${APIConstants.employeeLifeCycleContext}/job-offer/update/compliance-detail`,
            removeCtcStructureCompliance: `${APIConstants.employeeLifeCycleContext}/job-offer/remove/compliance-detail`,
            loadCtcComplianceType: `${APIConstants.employeeLifeCycleContext}/job-offer/compliance-info`,
            uploadOfferDocuments: `${APIConstants.employeeLifeCycleContext}/job-offer/upload/documents`,
            loadOffersScreen: `${APIConstants.employeeLifeCycleContext}/job-offer/all-detail`,
            getOfferDetailsByCode: `${APIConstants.employeeLifeCycleContext}/job-offer/detail`,
            // saveApprovalDataJobOffer: `${APIConstants.employeeLifeCycleContext}/job-offer/save-approval-data`,
            saveJobOfferTask: `${APIConstants.employeeLifeCycleContext}/job-offer/task/save`,
            // approveJobOffer: `${APIConstants.employeeLifeCycleContext}/job-offer/approve-job-offer`,
            approveJobOfferTask: `${APIConstants.employeeLifeCycleContext}/job-offer/task/approve`,
            saveDocuments: `${APIConstants.employeeLifeCycleContext}/job-offer/save/documents`,
            saveDocument: `${APIConstants.employeeLifeCycleContext}/job-offer/save/document`,
            updateDocuments: `${APIConstants.employeeLifeCycleContext}/job-offer/update/documents`,
            updateDocument: `${APIConstants.employeeLifeCycleContext}/job-offer/update/document`,
            loadPendingJobOffers: `${APIConstants.employeeLifeCycleContext}/job-offer/pending`,
            offerAcceptanceViaContact: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/via-contact`,
            offerAcceptanceEditPersonalDetails: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-personal-info`,
            offerAcceptanceUpdatePersonalDetails: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-personal-info`,
            offerAcceptanceAddNewContactDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-contact-info`,
            offerAcceptanceEditContactDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-contact-info`,
            offerAcceptanceAddNewWorkHistory: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-work-history`,
            offerAcceptanceEditWorkHistory: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-work-history`,
            offerAcceptanceAddBiometricDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-biometric`,
            offerAcceptanceUpdateBiometricDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-biometric`,
            offerAcceptanceAddNewEducation: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-education`,
            offerAcceptanceEditEducation: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-education`,
            offerAcceptanceAddNewSkill: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-skills`,
            offerAcceptanceEditSkill: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-skills`,
            offerAcceptanceAddNewFamilyDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-family-details`,
            offerAcceptanceEditFamilyDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-family-details`,
            offerAcceptanceSaveStatutoryDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-statutory-details`,
            offerAcceptanceUpdateStatutoryDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-statutory-details`,
            offerAcceptanceSaveNomineeDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/save-nomination-details`,
            offerAcceptanceUpdateNomineeDetail: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/update-nomination-details`,
            offerAcceptanceAccept: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/accept`,
            offerAcceptanceAcceptCandidateInfo: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/candidate-info`,
            offerAcceptanceMarkOverPendingVerification: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/mark-over-pending-verification`,
            offerAcceptanceAcceptOfferingInfo: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/offering-info`,
            offerAcceptanceVerifyDocuments: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/verify-document`,
            jobOfferRollOut: `${APIConstants.employeeLifeCycleContext}/job-offer/roll-out`,
            jobOfferTemplate: `${APIConstants.employeeLifeCycleContext}/offer-letter/template/keys`,
            // jobOfferPdfGenerate: `${APIConstants.employeeLifeCycleContext}/offer-letter/generate`,
            jobOfferRevokeOffer: `${APIConstants.employeeLifeCycleContext}/job-offer/revoke`,
            jobOfferResendMail: `${APIConstants.employeeLifeCycleContext}/job-offer/roll-out/resend`,
            jobOfferSummary: `${APIConstants.employeeLifeCycleContext}/job-offer/summary/date`,
            jobOfferRevise: `${APIConstants.employeeLifeCycleContext}/job-offer/revise`,
            jobOfferReopen: `${APIConstants.employeeLifeCycleContext}/job-offer/reopen`,
            jobOfferRevisionHistoryDetail: `${APIConstants.employeeLifeCycleContext}/job-offer/revision/history/detail`,
            confirmationActions: `${APIConstants.employeeLifeCycleContext}/confirmation/action`,
            offerAcceptanceOnBoardTheCandidate: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/approve`,
            offerDetailsByOfferCodeAndCompanyId: `${APIConstants.employeeLifeCycleContext}/job-offer/detail/company`,
            offerAcceptanceLeavesSuggest: `${APIConstants.employeeLifeCycleContext}/offer-acceptance/leaves/suggest`,
            loadBulkTransferStatistics: `${APIConstants.employeeLifeCycleContext}/bulk/transfer/statistics`,
            downloadTransferBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/transfer`,
            uploadTransferBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/transfer`,
            bulkTransferApprove: `${APIConstants.employeeLifeCycleContext}/bulk/transfer/approve`,
            bulkTransferNotApprove: `${APIConstants.employeeLifeCycleContext}/bulk/transfer/not-approve`,
            loadBulkAbscondingStatistics: `${APIConstants.employeeLifeCycleContext}/bulk/abscond/statistics`,
            downloadAbscondingBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/abscond`,
            uploadAbscondingBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/abscond`,
            bulkAbscondingApprove: `${APIConstants.employeeLifeCycleContext}/bulk/abscond/approve`,
            bulkAbscondingNotApprove: `${APIConstants.employeeLifeCycleContext}/bulk/abscond/not-approve`,
            loadBulkConfirmationStatistics: `${APIConstants.employeeLifeCycleContext}/bulk/confirmation/statistics`,
            downloadConfirmationBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/confirmation`,
            uploadConfirmationBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/confirmation`,
            bulkConfirmationApprove: `${APIConstants.employeeLifeCycleContext}/bulk/confirmation/approve`,
            bulkConfirmationNotApprove: `${APIConstants.employeeLifeCycleContext}/bulk/confirmation/reject`,
            loadBulkSeparationStatistics: `${APIConstants.employeeLifeCycleContext}/bulk/separation/statistics`,
            downloadSeparationBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/separation`,
            uploadSeparationBulkData: `${APIConstants.employeeLifeCycleContext}/bulk/separation`,
            bulkSeparationApprove: `${APIConstants.employeeLifeCycleContext}/bulk/separation/approve`,
            bulkSeparationNotApprove: `${APIConstants.employeeLifeCycleContext}/bulk/separation/reject`,
            bulkJobOfferDownloadSheet: `${APIConstants.employeeLifeCycleContext}/bulk/job-offer`,
            loadTerminationTasks: `${APIConstants.employeeLifeCycleContext}/abscond/termination/task`,
            approveTerminationTasks: `${APIConstants.employeeLifeCycleContext}/approve/abscond/termination`,
            rejectTerminationTasks: `${APIConstants.employeeLifeCycleContext}/reject/abscond/termination`,
            uploadBulkOfferData: `${APIConstants.employeeLifeCycleContext}/bulk/job-offer`,
            getOfferDocumentUrl: `${APIConstants.employeeLifeCycleContext}/job-offer/document/url`,
            journey: `${APIConstants.employeeLifeCycleContext}/journey`,
            journeyDetails: `${APIConstants.employeeLifeCycleContext}/journey/details`,
            resendAbscondingEmail: `${APIConstants.employeeLifeCycleContext}/abscond/resend`,
            addClearanceForm: `${APIConstants.employeeLifeCycleContext}/add/clearance/form`,
            companyClearanceForms: `${APIConstants.employeeLifeCycleContext}/get/company/clearance/forms`,
            getFnfDetails: `${APIConstants.employeeLifeCycleContext}/get/fnf`,
            getFnfClearanceDetails: `${APIConstants.employeeLifeCycleContext}/get/fnf/clearance`,
            addFnfClearanceParticulars: `${APIConstants.employeeLifeCycleContext}/add/clearance/particulars`,
            approveClearanceTask: `${APIConstants.employeeLifeCycleContext}/approve/clearance/task`,
            changeManager: `${APIConstants.employeeLifeCycleContext}/change/manager`,
            changeHr: `${APIConstants.employeeLifeCycleContext}/change/hr`,
            changeRole: `${APIConstants.employeeLifeCycleContext}/change/role/head`,
            changeWorkProfile: `${APIConstants.employeeLifeCycleContext}/work-profile/change`,
            humanCapitalDashboard: `${APIConstants.employeeLifeCycleContext}/human/capital/dashboard`,
            exitManagementDashboard: `${APIConstants.employeeLifeCycleContext}/exit/management/dashboard`,
        },
        employeeExpenseDetails: {
            loadUnclaimedExpenses: `${APIConstants.employeeExpenseDetailsContext}/expense/get/unclaimed`,
            loadClaimedExpensesById: `${APIConstants.employeeExpenseDetailsContext}/expense/get/claim`,
            loadClaimedExpensesByMonthAndYear: `${APIConstants.employeeExpenseDetailsContext}/expense/claim/get/month/year`,
            loadPendingClaimExpenses: `${APIConstants.employeeExpenseDetailsContext}/expense/claims/pending`,
            addExpense: `${APIConstants.employeeExpenseDetailsContext}/expense/add`,
            editExpense: `${APIConstants.employeeExpenseDetailsContext}/expense/update`,
            viewInvoice: `${APIConstants.employeeExpenseDetailsContext}/expense/invoice/link`,
            raiseClaim: `${APIConstants.employeeExpenseDetailsContext}/expense/claim/add`,
            approveClaim: `${APIConstants.employeeExpenseDetailsContext}/expense/claim/approve`,
            rejectClaim: `${APIConstants.employeeExpenseDetailsContext}/expense/claim/reject`,
            uploadExpenseInvoice: `${APIConstants.employeeExpenseDetailsContext}/expense/upload/invoice`,
            reopenExpense: `${APIConstants.employeeExpenseDetailsContext}/expense/claims/reopen`,
            expenseEmployeeDashboard: `${APIConstants.employeeExpenseDetailsContext}/expense/employee/dashboard`,
        },
        companyExpenseDetails: {
            companyExpenseDashboard: `${APIConstants.companyExpenseDetailsContext}/company/dashboard`,
        },
        managementExpenseDetails: {
            managementExpenseDashboard: `${APIConstants.managementExpenseDetailsContext}/management/dashboard`,
        },
        notifications: {
            getAllNotifications: `${APIConstants.notificationsContext}/get/all/pageable`,
            unReadNotifications: `${APIConstants.notificationsContext}/get/unread`,
            markAllAsRead: `${APIConstants.notificationsContext}/mark/all/read`,
            markSingleAsRead: `${APIConstants.notificationsContext}/mark/read`,
        },
        messenger: {
            chatroomCreator: `${APIConstants.messengerContext}/get/by/type`,
            chatroomGetEmployees: `${APIConstants.messengerContext}/get/employees`,
            chatroomByType: `${APIConstants.messengerContext}/get/by/type`,
            addChatroomViaContact: `${APIConstants.messengerContext}/add`,
            updateChatroomViaContact: `${APIConstants.messengerContext}/update`,
            getMessagesByChatRoomId: `${APIConstants.messengerContext}/message/get`,
            // sendMessagesInChatRoom: `${APIConstants.baseUrl}/app/chatroom/message`,
            sendMessagesInChatRoom: `${APIConstants.messengerContext}/message/add`,
            changeGroupAdmin:`${APIConstants.messengerContext}/change/admin`,
            addAttachment:`${APIConstants.messengerContext}/message/add/attachment`,
            getNotificationCount:`${APIConstants.messengerContext}/message/get/all/notifications`,
            chatRoomNotificationRead:`${APIConstants.messengerContext}/message/read/notification`,
        },
        helpdesk: {
            addCategory: `${APIConstants.helpdeskContext}/add/metadata`,
            addTicket: `${APIConstants.helpdeskContext}/ticket/add`,
            updateCategory: `${APIConstants.helpdeskContext}/update/metadata`,
            editTicket: `${APIConstants.helpdeskContext}/ticket/update`,
            loadCategories: `${APIConstants.helpdeskContext}/get/metadata`,
            feedbackCount: `${APIConstants.helpdeskContext}/ticket/feedback/count`,
            ticketCounts: `${APIConstants.helpdeskContext}/ticket/get/count`,
            ticketsByStatus: `${APIConstants.helpdeskContext}/ticket/get/status`,
            assignedTickets: `${APIConstants.helpdeskContext}/ticket/get/assign`,
            ticketWatcher: `${APIConstants.helpdeskContext}/ticket/get/watcher`,
            dashboardSummary: `${APIConstants.helpdeskContext}/dashboard`,
            changeTicketStatus: `${APIConstants.helpdeskContext}/ticket/status/change`,
            feedbackOnClosedTicket: `${APIConstants.helpdeskContext}/ticket/add/feedback`,
            getCategoryAndSubCategory: `${APIConstants.helpdeskContext}/get/metadata/categories`,
            getAllTicketsRaisedByMe: `${APIConstants.helpdeskContext}/ticket/get/all`,
        },
        companyPolicyDocument: {
            addPolicy: `${APIConstants.companyPolicyDocument}/add`,
            allPolicy: `${APIConstants.companyPolicyDocument}/all`,
            myPolicy: `${APIConstants.companyPolicyDocument}/employee/new/assigned`,
            oldPolicy: `${APIConstants.companyPolicyDocument}/employee/old/assigned`,
            acknowledgePolicy: `${APIConstants.companyPolicyDocument}/acknowledge`,
            employeeAcknowledgePolicy: `${APIConstants.companyPolicyDocument}/employee/acknowledged`,
            expiredPolicies: `${APIConstants.companyPolicyDocument}/expired/all`,
            viewPolicyDocument: `${APIConstants.companyPolicyDocument}/url`,
            policyDetails: `${APIConstants.companyPolicyDocument}/all/details`,
            policySendReminder: `${APIConstants.companyPolicyDocument}/send/reminder`,
            policyExpire: `${APIConstants.companyPolicyDocument}/expire`,
            policyDetailsById: `${APIConstants.companyPolicyDocument}/get/by/id`
        },
        employeeIdentityDocuments: {
            getDocumentCategoryTypes: `${APIConstants.employeeIdentityDocument}/get/types`,
            getDocumentStatuses: `${APIConstants.employeeIdentityDocument}/get/statuses`,
            teamDocuments: `${APIConstants.employeeIdentityDocument}/request/dashboard`,
            requestDocument: `${APIConstants.employeeIdentityDocument}/request/add`,
            getDashboardStatistics: `${APIConstants.employeeIdentityDocument}/request/dashboard/statistics`,
            myDocumentUpload: `${APIConstants.employeeIdentityDocument}/add`,
            myDocuments: `${APIConstants.employeeIdentityDocument}/get/all`,
            documentCategories: `${APIConstants.employeeIdentityDocument}/get/categories`,
            documentRequestTask: `${APIConstants.employeeIdentityDocument}/get/request/task`,
            documentTask: `${APIConstants.employeeIdentityDocument}/get/document/task`,
            acceptDocument: `${APIConstants.employeeIdentityDocument}/accepted`,
            rejectDocument: `${APIConstants.employeeIdentityDocument}/rejected`,
            viewDocument: `${APIConstants.employeeIdentityDocument}/url`,
            sendReminder: `${APIConstants.employeeIdentityDocument}/send/reminder`,

        },
        tds: {
            getActiveCategories: `${APIConstants.tdsContext}/categories/active`,
            initiateDeclaration: `${APIConstants.tdsContext}/employee/tax/declaration/initiate`,
            addTdsComponent: `${APIConstants.tdsContext}/employee/tax/declaration/component/add`,
            getSavedComponent: `${APIConstants.tdsContext}/employee/tax/declaration/detail`,
            addRentTdsComponent: `${APIConstants.tdsContext}/employee/tax/declaration/rent/add`,
            submitDeclaration: `${APIConstants.tdsContext}/employee/tax/declaration/submit`,
            declarationHistory: `${APIConstants.tdsContext}/employee/tax/declaration/history`,
        },
        inquiryForm: {
            addInquiryForm: `${APIConstants.inquiryFormContext}/add`,
            getTypes: `${APIConstants.inquiryFormContext}/get/types`,
            getInquiryFormById: `${APIConstants.inquiryFormContext}/get/by/id`,
            addFormAnswer: `${APIConstants.inquiryFormContext}/add/answer`,
            getAllInquiryForms: `${APIConstants.inquiryFormContext}/get/all`,
            getEmployeeAllInquiryForms: `${APIConstants.inquiryFormContext}/employee/get/all`,
            getEmployeeSubmittedFormById: `${APIConstants.inquiryFormContext}/employee/get`,
            assignInquiryForm: `${APIConstants.inquiryFormContext}/assign`,
            inquiryFormOverview: `${APIConstants.inquiryFormContext}/overview`,
            inquiryFormResponsesByCandidate: `${APIConstants.inquiryFormContext}/responses`,
            inquiryFormResponsesByQuestion: `${APIConstants.inquiryFormContext}/question/responses`,
            formSendReminder: `${APIConstants.inquiryFormContext}/send/reminder`,
            getFormQuestions: `${APIConstants.inquiryFormContext}/questions`,
        }
    };

    static getEndpoints() {
        return this.endPoints;
    }
}

class CRMAPIConstants {
    static crmBaseUrl = Constants.getCRMBaseUrl();

    static leadsContext = `${CRMAPIConstants.crmBaseUrl}/leads`;

    static endPoints = {
        leads: {
            submitContactDetail: `${CRMAPIConstants.leadsContext}/add/demo/inquiry`,
        }
    }

    static getEndpoints() {
        return this.endPoints;
    }
}

export default APIConstants;
export {CRMAPIConstants};
